# Generated by Django 5.1.6 on 2025-05-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_create_at_user_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "남성"), ("F", "여성")],
                max_length=1,
                verbose_name="성별",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="old_cart",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
